#!/usr/bin/python
#
#  Copyright Luis de Bethencourt Guimera, Andrew Hunter 2008
#
#    This program is free software; you may redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the Free 
#    Software Foundation; either version 2 of the License, or (at your option) 
#    any later version.
#
#    This program is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
#    FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
#    more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

try:
    import gtk
    import pygtk
    import gobject
    import os
    from gtk import glade
    import flickroll
    import threading
    import time
except:
    import_error = gtk.MessageDialog (None, gtk.DIALOG_MODAL, gtk.MESSAGE_ERROR, \
        gtk.BUTTONS_OK, ('You need to install python bindings for gtk and/or glade \
        ("python-gtk2 & python-glade2" in debian/ubuntu)'))
    import_error.run()
    sys.exit(1)

class FlickBook:
    def __init__(self):
        self.gladefile = "gui.glade"
        self.wTree = gtk.glade.XML(self.gladefile)
        self.window = self.wTree.get_widget("mainWindow")
        self.pitchScale = self.wTree.get_widget("pitchScale")
        self.controls = self.wTree.get_widget("controlsBox")
        self.separator = self.wTree.get_widget("hseparator")
        self.image = self.wTree.get_widget("image")
        self.imageBox = self.wTree.get_widget("imageBox")
        self.splitBox = self.wTree.get_widget("splitBox")
        self.images = [self.wTree.get_widget("image0"), \
                       self.wTree.get_widget("image1"), \
                       self.wTree.get_widget("image2"), \
                       self.wTree.get_widget("image3") ]

        dic = { "on_newThreadButton_clicked" : self.next,
            "on_syncButton_clicked" : self.sync,
            "on_fullscreenButton_clicked" : self.fullscreen,
            "on_key_press_event" : self.keyPress,
            "on_modeButton_clicked" : self.mode_switch,
            "on_mainWindow_destroy" : gtk.main_quit}
        self.wTree.signal_autoconnect(dic)

        black = gtk.gdk.rgb_get_colormap().alloc_color('black')
        self.window.modify_bg(gtk.STATE_NORMAL, black)

        pixbuf = gtk.gdk.pixbuf_new_from_file_at_size('../files/flickbook.jpg', 600, 600)
        self.image.set_from_pixbuf(pixbuf)
        pixbuf1 = gtk.gdk.pixbuf_new_from_file_at_size('../files/flickbook.jpg', 300, 300)
        self.images[0].set_from_pixbuf(pixbuf1)
        self.images[1].set_from_pixbuf(pixbuf1)
        self.images[2].set_from_pixbuf(pixbuf1)
        self.images[3].set_from_pixbuf(pixbuf1)

        self.flickroll = flickroll.FlickRoll()
        self.flickroll.get_first_photo()
        self.pitch = 30
        self.loop_amount = 42
        self.c = 0
        self.i = 0
        self.height = 600
        self.width = 600
        self.split_height = 300
        self.split_width = 300
        self.mode = True
        self.d = 0
        self.flickroll_loop()
        self.time_id = gobject.timeout_add(2000, self.time_out_cb)

    def next(self, widget):
        file = '%d.jpg' % self.c
        if os.path.exists(file):
            self.image_change(file)
        if self.c < self.loop_amount:
            self.c += 1
        else:
            self.c = 0

    def image_change(self, file):
        if self.mode:
            pixbuf = gtk.gdk.pixbuf_new_from_file_at_size(file, self.width, self.height)
            self.image.set_from_pixbuf(pixbuf)
        else:
            pixbuf = gtk.gdk.pixbuf_new_from_file_at_size(file, self.split_width, self.split_height)
            self.images[self.d].set_from_pixbuf(pixbuf)
            if self.d < 3:
                self.d += 1
            else:
                self.d = 0
            

    def new_thread(self, widget):
        self.flickroll.get_first_photo()

    def flickroll_loop(self):
        filename = '%d.jpg' % self.i
        self.flickroll.get_next_photo(filename)
        if self.i < self.loop_amount:
            self.i = self.i + 1
        else:
            self.i = 0

    def sync(self, widget):
        gobject.source_remove(self.time_id)
        self.time_id = gobject.timeout_add(int(60000 / self.pitch), self.time_out_cb)
        self.next(self.image)

    def fullscreen(self, widget):
        self.window.fullscreen()
        self.controls.hide()
        self.separator.hide()
        self.width = gtk.gdk.screen_width()
        self.height = gtk.gdk.screen_height()
        self.split_width = self.width / 2
        self.split_height = self.width / 2
        self.next(self.window)

    def unfullscreen(self, widget):
        self.window.unfullscreen()
        self.controls.show()
        self.separator.show()
        self.width = 600
        self.height = 600
        self.split_width = 300
        self.split_height = 300
        self.next(self.window)

    def keyPress(self, widget, event):
        key = gtk.gdk.keyval_name(event.keyval)
        if key == 'Escape':
            self.unfullscreen(self.window)
        if key == 'Up':
            pitch = self.pitchScale.get_value()
            self.pitchScale.set_value(pitch + 1)  
        if key == 'Down':
            pitch = self.pitchScale.get_value()
            self.pitchScale.set_value(pitch - 1)
        if key == 's':
            self.sync(self.window)
        if key == 'f':
            self.fullscreen(self.window)
        if key == 'm':
            self.mode_switch(self.window)

    def mode_switch(self, widget):
        if self.mode == True:
            self.imageBox.hide()
            self.splitBox.show()
            self.mode = False
        else:
            self.imageBox.show()
            self.splitBox.hide()
            self.mode = True

    def time_out_cb(self):
        self.flickroll_loop()
        self.next(self.image)
        if self.pitch != self.pitchScale.get_value():
            self.pitch = self.pitchScale.get_value()
            self.time_id = gobject.timeout_add(int(60000 / self.pitch), self.time_out_cb)
            return False
        else:
            return True

if __name__ == "__main__":
    flickbook = FlickBook()
    gtk.gdk.threads_init()
    gtk.main()
